### ISSUE TITLE
Is there are plugin structure planned?

### ISSUE THREAD

**Issue by pscheit** [moll/js-must#12]
Hey there, your attempt to write another assertion library sounds compromising.
Are you planning to write a plugin structure like in chai? I have a lot of complex tests and would love to have something "easier" than the chaijs plugin structure. Maybe something more intuitive ;)

best regards and thank you
philipp

**Comment by landau** [comment]
This would be great. I really enjoy the combo of chai + sinon-chai. I wish I could do the same here.

**Comment by moll** [comment]
Good news, everyone! Made some progress:

> I pondered over the `insist` function a little and ended up with the idea to export it as `Must.prototype.assert` (https://github.com/moll/js-must/blob/77616e892cfaed31181d634b544e46bd85d5e421/must.js#L1028).
> 
> In short, it works like any assert function ever:
> ```javascript
> Must.prototype.truthy = function() {
>   this.assert(this.actual, "be truthy")
> }
> ```
> 
> Given an object with `{expected}` as the third argument sets the `expected` property on the assertion error _and_ concatenates its stringified value to the end of the message string:
> 
> ```javascript
> Must.prototype.null = function() {
>   this.assert(this.actual === null, "be", {expected: null})
> }
> ```
> 
> If you give a function instead of a string, that function will be called for the message should the assertion fail. You can still pass `expected` in an options object, but instead of concatenating, it'll only be for `AssertionError`.

Given the above, to add matchers, one could just assign them to `Must.prototype`, call `Must.prototype.assert` within it and call it a day. Would something like this handle most cases?

Thanks in advance!

**Comment by JohnnyEstilles** [comment]
Let us know when you publish these so we can start working on our plugins.

**Comment by moll** [comment]
Will do. I'm kind of waiting for your feedback first actually to know if it does the trick or needs something further. :-)
You can work off of master by installing it with NPM: `npm i git+https://github.com/moll/js-must.git`.

**Comment by JohnnyEstilles** [comment]
I'll start working on another plugin tomorrow morning.

**Comment by JohnnyEstilles** [comment]
@moll, check out [must-sinon](https://github.com/JohnnyEstilles/must-sinon). I still have a few matchers to add, but the basic plugin functionality is in place and working. So, AFAICT ... Must.js is plugin ready. :-)

**Comment by moll** [comment]
Checking it out now. You gave me an idea with those placeholder vars — perhaps rather than always concatenating `opts.expected` to the assertion failure message, do so only if the message has a placeholder `%s`. Any pros and cons you see?

**Comment by JohnnyEstilles** [comment]
Using placeholders seems like a good idea to me. :-)

**Comment by moll** [comment]
They might indeed, but I've got a sneaky feeling we should start with no interpolation nor concatenating initially. The risk with more features off the bat is that it might prevent something better designed later.

**Comment by JohnnyEstilles** [comment]
I understand your concern. The upside is that interpolation would allow you to construct a more readable message, since you can interpolate the `expected` value where it would grammatically fit best, instead of a fixed, concatenated place within the message. The flexibility offered by interpolation is worth considering.

That said, you're in a much better position to gauge whether a feature like this may or may not hinder future features/design.

**Comment by moll** [comment]
The stringifying function Must uses for concatenation is currently exported as `Must.stringify`, so after removing both the concatenation (and not _yet_ adding interpolation), one can still prepare a message with it before calling `Must.prototype.assert`.

**Comment by JohnnyEstilles** [comment]
Yeah ... didn't realize until now that you've exported `Must.stringify` going to use it in `must-sinon`

**Comment by moll** [comment]
My bad. Haven't documented the developer facing API.
I remembered why I added concatenation to `Must.protoytype.assert` in the first place — it was to get lazy stringifying — to not do the work of serialization until the assertion actually failed. You might want to pass a function as a message to `Must.prototype.assert` to get the same behavior now.

**Comment by jtwebman** [comment]
@moll I went ahead and gave it a shoot with Targaryen plugin called [must-targaryen](https://github.com/jtwebman/must-targaryen). Could you take a look and give any suggestions if something looks wrong?

**Comment by nwinch** [comment]
I've added another to the mix for JSX comparison - [must-jsx](https://github.com/nwinch/must-jsx).

**Comment by moll** [comment]
Thanks @JohnnyEstilles, @jtwebman and @nwinch for pitching in. I linked to the three modules above in the README: https://github.com/moll/js-must#plugins.

👍 everyone for exporting a function to be called with `Must`. That's future proof.

I'll close this issue as tweaking Must for extensibility is an ongoing task. So far `this.assert` seems to cover most cases, apart from one suggestion @nwinch made in https://github.com/moll/js-must/issues/44.
