### ISSUE TITLE
Custom Changes

### ISSUE THREAD

**Issue by saulshanabrook** [moll/js-must#32]
Is it currently possible to change the data midway through an assertion?

For example I have a want to resolve a promise (using `eventually`) then select the `value` key from the object returned, then convert that JSON string into a JS object, then do a check on it.

**Comment by moll** [comment]
Hey,

You could do that via any regular way you handle promises. Like:
```javascript
promise.then((p) => JSON.parse(p.field)).must.then.eql({name: "John"})
```
Would that work?

**Comment by saulshanabrook** [comment]
Yep! I would also have to handle if the promise failed, right?

**Comment by moll** [comment]
Not necessarily. If you pass the whole promise to something that waits on it, it'll blow up if your JSON parsing failed. Must uses the same mechanism — it just rejects the promise if the assertion failed.
I wrote a small example here: https://github.com/moll/js-must/issues/22#issuecomment-111840555

**Comment by saulshanabrook** [comment]
Awesome, thank you!

**Comment by moll** [comment]
Yippie!
