### ISSUE TITLE
Strange issue with Promises and Mocha

### ISSUE THREAD

**Issue by capelio** [moll/js-must#55]
Using mocha, must, and promises:

```js
it('works as expected', () => {
  return expect(Promise.resolve([1, 2, 3])).to.resolve.to.array()
})

it('throws a TypeError', () => {
  return expect(Promise.resolve([1, 2, 3])).to.resolve.to.be.an.array()
})
```

And the TypeError:

```
     TypeError: Function.prototype.toString is not generic
      at Must.toString (native)
      at Function.prepareStackTrace (node_modules/source-map-support/source-map-support.js:365:16)
      at Must.assert (node_modules/must/lib/thenable.js:20:41)
      at apply (node_modules/must/node_modules/lodash.wrap/node_modules/lodash._createwrapper/index.js:72:25)
      at Must.wrapper (node_modules/must/node_modules/lodash.wrap/node_modules/lodash._createwrapper/index.js:415:12)
      at Must.array (node_modules/must/must.js:314:8)
      at Must.exports.then (node_modules/must/lib/thenable.js:26:6)
```

Maybe I'm reading the docs incorrectly, but this _seems_ like it should work.

**Comment by moll** [comment]
Hey! Sorry you're facing trouble. I'll take a look!

**Comment by moll** [comment]
I'm having slight trouble reproducing this. The second example above seems to run under Node v4 and Node v7. I think this is related to the source-map-support plugin. Would you mind telling which version of it are you using? I suspect what's causing it, but I'd like to be certain. Thanks!

**Comment by capelio** [comment]
Ah, good point. I should have mentioned I'm using babel with mocha, didn't think of it at the time.

A `npm ls` gives me `source-map-support@0.4.6`

I've run the tests both with and without registering babel to mocha. The TypeError only throws when running with babel registered. Everything's kosher once babel is taken out of the equation.

**Comment by capelio** [comment]
And by the way, thanks a **ton** for Must.js. Best assertion library out there :)

**Comment by moll** [comment]
Thanks for the clarification! I tweaked the implementation of `Must.prototype.be`. Would you mind installing from master, this repo, and confirm if that fixes it for you. If it does, I'll publish a release.

Thanks for the love, too! What do you particularly like, so I'll know to bring that up when occasionally promoting it? :)

**Comment by capelio** [comment]
Nicely done! Pulled latest master, ran `npm link`, pulled it into my project with `npm link must`, and both tests now pass.

Here's why I love Must:

* Awesome Promise assertions that let me test for resolve/reject behavior
* Intuitive API, few surprises, succinctly documented
* Enough API sugar to maximize the fluency of my tests
* Doesn't use non-strict JS features, which means I can bundle my tests written with Babel, Mocha, and Must into a suite that can be run in all the browsers we support via Sauce Labs (lookin at you `chai`)
* Doesn't force me to overload `Object`

**Comment by moll** [comment]
Thanks for confirming and for elaborating! :)
Sent v0.13.4 out there. Should really tweak a few other things and release v1. This 0.x thing has gone for far too long. This is not GMail with its infinite beta!
