### ISSUE TITLE
API.md is broken on GitHub

### ISSUE THREAD

**Issue by Ionaru** [moll/js-must#65]
The API.md page is somewhat broken on GitHub, headers aren't displayed as headers and some line-breaks aren't working properly.

**Comment by moll** [comment]
Ah, damn. GitHub must've changed this behavior. Thank you for bringing this up and for your PR! I'll apply it in a sec and regenerate other Markdown files for my other projects, too.

**Comment by moll** [comment]
Well that took longer than expected! 😇 
Thanks again, Jeroen! I fixed my script to generate docs correctly, too, and tweaked it to append the anchor name to the header line.
